### ISSUE TITLE
Sonic colors has invisible menu

### ISSUE THREAD

**Issue by riqbal007** [OatmealDome/DolphiniOS-Issue-Tracker#37]
Invisible menu on Sonic colors

**Comment by OatmealDome** [comment]
[This is apparently an issue with the Android version of Dolphin](https://www.reddit.com/r/DolphinEmulator/comments/enaeyq/sonic_colors_on_android_has_invisible_huds_and/). (DolphiniOS is a port of the Android version.)

Please file a bug report to the Dolphin developers if possible. Note that because DolphiniOS is not supported by the official Dolphin developers, any testing must be done using an Android phone with the latest Google Play build.
