### ISSUE TITLE
Way to side load via Xcode.. jailbreak required?

### ISSUE THREAD

**Issue by bryan1anderson** [OatmealDome/DolphiniOS-Issue-Tracker#42]
Is jailbreaking required to get this to work? Or can I build and compile using Xcode?

**Comment by Simonx22** [comment]
A jailbreak is required at this time.

**Comment by jankais3r** [comment]
Is this because of JIT limitations? UTM hast JIT also on non-jb devices...

**Comment by OatmealDome** [comment]
@jankais3r Dolphin attempts to allocates a large amount of virtual memory to help make GC/Wii memory emulation faster ("fastmem"), and iOS refuses because it's too big. The ``dynamic-codesigning`` entitlement gives us more virtual memory to play with, which is where the jailbreak requirement comes from.

**Comment by jankais3r** [comment]
Would it be possible to share the IPA, so people without jailbreak can assign those entitlements via the yesterday published [exploit](https://twitter.com/jankais3r/status/1256120419062550528)? I believe that any entitlement can be achieved, not just the sandbox escape used in the example.

**Comment by OatmealDome** [comment]
@jankais3r It does appear to be possible to assign ``dynamic-codesigning``. I'd need to [implement some workaround used in UTM](https://github.com/utmapp/UTM/issues/32) before a release though, since I do use ``PT_TRACEME``.
