### ISSUE TITLE
Kirby: Air Ride shows black area when driving around in courses

### ISSUE THREAD

**Issue by Coolaaron88** [OatmealDome/DolphiniOS-Issue-Tracker#59]
**Describe the issue**
When you load up Kirby Air Ride, and select a course to play, when you are driving around the entire course is black. 

**How to reproduce**
Open up Kirby Air Ride on Dolphin for iOS and play a course (dont know if it happens on other platforms)

**Expected result**

Should load the course with no issues 

**Device information**
 - Device [ 1st Gen 11 inch iPad Pro ]
 - OS [e.g. iOS 13.4.1]
 - DolphiniOS version (go to the Settings tab) [e.g. v2.2.0]

**Comment by OatmealDome** [comment]
Metal doesn't expose LogicOps support, which Kirby's Air Ride uses heavily, causing the incorrect rendering. This also affects macOS when using Vulkan over MoltenVK.

The only way to fix this issue is to get Apple to add public LogicOps support to Metal. It's literally already there, but they're not exposing it to developers.

MoltenVK is tracking this bug at KhronosGroup/MoltenVK#374.
