### ISSUE TITLE
Docs on how to build for non-jailbroken device

### ISSUE THREAD

**Issue by eurobob** [OatmealDome/DolphiniOS-Issue-Tracker#86]
**Describe the feature you'd like**
I can't jailbreak my device for work related reasons, is it possible to get some instructions on how to make this work by building myself with Xcode?

**Device information**
 - iPhone X
 - iOS 13.5

**Comment by Simonx22** [comment]
The non-jailbroken his only work on 13.4.1 or lower.

**Comment by eurobob** [comment]
@OatmealDome @Simonx22 I don't think this issue should be closed. I understand that an exploit is used for loading the app pre-13.5, but why do I have to use the alt store. Why can I not simply download the code and build onto my device. Surely this renders the non-jailbroken exploit obsolete?

**Comment by OatmealDome** [comment]
> Why can I not simply download the code and build onto my device. 

Dolphin requires the ability to allocate a large amount of virtual memory for emulating the GC/Wii RAM. iOS, by default, [restricts the amount of virtual memory that can be allocated by a single application](https://github.com/apple/darwin-xnu/blob/master/osfmk/arm/pmap.c#L9868) to much less than what Dolphin requires.

Because of this, we must use the `dynamic-codesigning` entitlement, which [increases the virtual memory limit](https://github.com/apple/darwin-xnu/blob/master/tests/jumbo_va_spaces_28530648.c). This entitlement is [only granted by Apple to very specific applications](http://newosxbook.com/ent.jl?ent=dynamic-codesigning&osVer=iOS13), and third party developers are not allowed to use it. This can only be bypassed by using a jailbroken device or with the [psychicpaper exploit](https://siguza.github.io/psychicpaper/) on pre-13.5 devices.
