### ISSUE TITLE
Shoulder Buttons Don't Work GameCube

### ISSUE THREAD

**Issue by N-Games** [OatmealDome/DolphiniOS-Issue-Tracker#98]
**Describe the issue**
The shoulder buttons don't work

**How to reproduce**
Use the shoulder buttons in a game

For example: 
1. Open a game
2. Use the shoulder buttons

**Expected result**
That they would work

**Device information**
 - Device: iPhone 6
 - OS: iOS 12.4.7
 - Jailbreak: Checkra1n
 - DolphiniOS version: 2.2.3(4)

Video: https://www.youtube.com/watch?v=vpTyshSSV1Q

**Comment by xoniq** [comment]
Try to set both shoulder L and R as analog L and R to the same button. The issue is, the GC has controllers with two actions per trigger. You can press them lightly => digital, and hard => analog. I had this with Metroid Prime, which uses the digital button, so I put both on each shoulder button, and now it works just fine.

**Comment by N-Games** [comment]
Ok, the problem were the corrupted .ini files
